### ISSUE TITLE
twitter card not completely extracted

### ISSUE THREAD

**Issue by homekititalia** [AlfredoRamos/phpbb-ext-seo-metadata#20]
Hi,
Compliment for your work!
Works fine, but i not understand why not extract twitter card
Extract only 
```
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@homekititalia1">
```
but 
tag `<meta name="twitter:image"> `not displayed.
tag `<meta name="twitter:title">` not displayed.
tag `<meta name="twitter:description">` not displayed.
i'm using version 1.2.0-beta2

**Comment by AlfredoRamos** [comment]
Hi,

Do you have Open Graph enabled? If so, that's normal since those "missing" tags are read from Open Graph.

I explicitly remove that metadata from the template if both options are enabled:

https://github.com/AlfredoRamos/phpbb-ext-seo-metadata/blob/4faa6016d1997ae25cc7e471f2f5f2bdf3421089/includes/helper.php#L184-L192

Reference: [https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#twitter-cards-and-open-graph](Getting started with cards: Twitter Cards and Open Graph)

**Comment by homekititalia** [comment]
Ok, thanks for answer. Why you remove if both enable?

**Comment by AlfredoRamos** [comment]
As I said in my previous message, is to avoid duplicate meta tags, if you don't specify:

```html
<meta name="twitter:image" content="...">
```

It will fallback to the value of:

```html
<meta property="og:image" content="...">
```

If you disable Open Graph, it will show the "missing" Twitter Card meta tags.
