### ISSUE TITLE
PHP Notice: in file [ROOT]/ext/alfredoramos/seometadata/event/listener.php on line 126: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by Bastien59960** [AlfredoRamos/phpbb-ext-seo-metadata#65]
I, in some page of my forum not all, i got this message : 

`[phpBB Debug] PHP Notice: in file [ROOT]/ext/alfredoramos/seometadata/event/listener.php on line 126: Trying to access array offset on value of type null`

https://bernard.debucquoi.com/forum/viewtopic.php?f=14&t=15544

I use Phpbb3.3 and the latest version of your extension.

**Comment by AlfredoRamos** [comment]
Hi,

Please, always specify the version of the extension you are using, because I guess you downloaded this extension from phpbb.com and there the latest one usually is not available because of the approval process.

The error you are reporting was fixed in version 1.3.1 (#48) but it has been in the validation queue for almost 5 months at phpbb.com and I don't know how much longer it will take.

I would recommend you to use a beta version (1.4.0-beta3 right now), which has been updated more frequently.

https://www.phpbb.com/customise/db/extension/seo_metadata/support/topic/208496

Please try it and report back if the issue has been fixed for you.

**Comment by Bastien59960** [comment]
Work great problem solved, thanks a lot for this extension !
