### ISSUE TITLE
Error update to 1.1.0

### ISSUE THREAD

**Issue by olalavui** [AlfredoRamos/phpbb-ext-seo-metadata#9]
Use ext version 1.0.0

I have Disable -> Delete data -> Delete all the files inside {PHPBB_ROOT}/ext/alfredoramos/seometadata/ -> Download on: https://github.com/AlfredoRamos/phpbb-ext-seo-metadata/releases/tag/1.1.0 -> upload & extract -> enable ext & have error

![image](https://user-images.githubusercontent.com/187494/57002260-4e321300-6be8-11e9-8368-76c4c6cf9d09.png)

`Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.

A module already exists: ACP_SEO_METADATA`

Can you help me?

**Comment by AlfredoRamos** [comment]
Hi,

Which version did you update from? Are you sure you deleted the extension data before copying the new files?

That's indeed an error, but it only happens when the data it's not deleted before copying the new version.

You could fix it by:

- Disabling and deleting data of version 1.1.0
- Installing again the previous version you were using
- Disabling and installing the previous version
- Finally installing version 1.1.0

This method is the proper way to do it however it could be tedious.

Another option would be to delete the module manually:

- ACP > System > Module management > Administration Control Panel
- Select Extensions
- Find `ACP_SEO_METADATA` and click on the red icon and confirm to delete it

This error was caused because I changed some file names (migrations), but this won't happen again once it's approved by the phpBB extension validation team.

**Comment by AlfredoRamos** [comment]
I'm closing this as any of the above methods would fix your issue, if not, reopen this issue.
